name: 'Send Email Composite Action'
description: 'A composite action to send an email using Microsoft Graph'

inputs:
  ToEmail:
    description: 'Recipient email address(es), comma-separated if multiple'
    required: true
  CcEmail:
    description: 'Cc email address(es), comma-separated if multiple'
    required: false
  Subject:
    description: 'Subject of the email'
    required: true
  emailBodyBase64:
    description: 'Base64-encoded body content'
    required: true
  FromEmail:
    description: 'Sender email address (comma-separated if multiple)'
    required: true
  AzureCredentialsJson:
    description: 'Azure credentials JSON secret'
    required: true


runs:
  using: "composite"
  steps:
    - name: 'Send Email Using PowerShell Script'
      shell: pwsh
      run: |
        try { ${{ github.action_path }}/Send-MgGraphEmail.ps1 -ToEmail ${{ inputs.ToEmail }} -CcEmail ${{ inputs.CcEmail }} -Subject ${{ inputs.Subject }} -emailBodyBase64 ${{ inputs.emailBodyBase64 }} -FromEmail ${{ inputs.FromEmail }} -AzureCredentialsJson ${{ inputs.AzureCredentialsJson }} } catch { Write-Host "::Error::Unexpected error when running action ($($_.Exception.Message))"; exit 1 }
